### ISSUE TITLE
This page can't load Google Maps correctly. Do you own this website?

### ISSUE THREAD

**Issue by mrhrifat** [bradtraversy/wildfire-tracker#4]
I am creating this web app with `ReactJS`. But I am having an error of 
> This page can't load Google Maps correctly. Do you own this website?

on browser view.

#### Project Info
- I have created `no billing` **free** `API Key` on [Google Developer](https://console.cloud.google.com/apis/)
- I have created `.env` on my React project & use with `process.env.REACT_APP_API_KEY 
    - I also try with direct `API` Key
- I have installed & imported `google-map-react`

#### API Info
- I have enable `JavaScript Map API`
- App restriction selected `HTTP referrers(web sites)
- Website restriction set 
```
*localhost:3000
http://localhost:3000
```
- API restriction 
    - Restrict Key -> Map JavaScript API

#### Problem
- I have clear `cached & cookies` & `restart` server many times but it show me 
> This page can't load Google Maps correctly. Do you own this website? For development purposes only

#### Code
```js
import GoogleMapReact from 'google-map-react'
import '../style/index.css'

const Map = ({ center, zoom }) => {
    return (
        <div className='map'>
            <GoogleMapReact
                bootstrapURLKeys={{
                    key: process.env.REACT_APP_API_KEY
                }}
                defaultCenter={center}
                defaultZoom={zoom}
            >

            </GoogleMapReact>
        </div>
    )
}
Map.defaultProps = {
    center: {
        lat: 42.3265,
        lng: -122.8756
    },
    zoom: 3
}

export default Map
```

**Comment by shptk** [comment]
were you able to tackle it, I'm facing similar roadblocks!! @mrhrifat

**Comment by mrhrifat** [comment]
You need to have an premium account (means have to add credit card details on google) then you'll be able to do it.
